services:
  - type: web
    name: fastapi-api-mobile
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 1 -k uvicorn.workers.UvicornWorker --bind=0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db-mobile-test
          property: connectionString
